"""Product Requirements Document (PRD) Schema."""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class AcceptanceCriterion(BaseModel):
    id: str = Field(..., description="Unique criterion identifier, e.g., AC-1")
    given: str = Field(..., description="Initial condition / context")
    when: str = Field(..., description="Action or event triggered")
    then: str = Field(..., description="Expected outcome / post-condition")


class UserStory(BaseModel):
    id: str = Field(..., description="Unique user story identifier, e.g., US-101")
    title: str = Field(..., description="User story summary")
    as_a: str = Field(..., description="User persona")
    i_want: str = Field(..., description="Desired capability")
    so_that: str = Field(..., description="Business value or rationale")
    acceptance_criteria: List[AcceptanceCriterion] = Field(default_factory=list)
    priority: str = Field(default="medium", description="Priority level: high, medium, low")


class OperationalConstraint(BaseModel):
    category: str = Field(..., description="Category: security, compliance, performance, tech_stack")
    description: str = Field(..., description="Constraint detail")
    mandatory: bool = Field(default=True)


class ProductRequirementsDocument(BaseModel):
    """PRD generated by Tier 1 Product Manager."""
    version: str = Field(default="1.0.0", description="Semantic version of the PRD")
    title: str = Field(..., description="Project / Product title")
    executive_summary: str = Field(..., description="High-level product vision and goals")
    target_personas: List[str] = Field(default_factory=list)
    user_stories: List[UserStory] = Field(default_factory=list)
    operational_constraints: List[OperationalConstraint] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
