"""Task Ticket, Dependency DAG, and Kanban State Schemas."""
from typing import List, Dict, Any, Optional
from enum import Enum
from pydantic import BaseModel, Field


class TicketStatus(str, Enum):
    BACKLOG = "backlog"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    DONE = "done"
    BLOCKED = "blocked"


class TaskComplexity(str, Enum):
    SMALL = "S"
    MEDIUM = "M"
    LARGE = "L"


class TaskTicket(BaseModel):
    """Atomic issue ticket dispatched onto virtual Kanban board."""
    ticket_id: str = Field(..., description="E.g., TSK-101")
    title: str = Field(...)
    description: str = Field(...)
    domain_tags: List[str] = Field(
        default_factory=list,
        description="Domain tags for Agent Router dispatch: api, db, scraping, ui, layout, a11y, design-system, security"
    )
    assigned_role: Optional[str] = Field(
        default=None,
        description="Assigned specialist agent: engineer-backend, engineer-frontend, engineer-ux"
    )
    status: TicketStatus = Field(default=TicketStatus.BACKLOG)
    complexity: TaskComplexity = Field(default=TaskComplexity.MEDIUM)
    dependencies: List[str] = Field(default_factory=list, description="IDs of prerequisite tickets")
    acceptance_criteria: List[str] = Field(default_factory=list)
    git_branch: Optional[str] = Field(default=None)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TaskDAG(BaseModel):
    """Directed Acyclic Graph of tickets generated by Tier 3 Engineering Manager."""
    version: str = Field(default="1.0.0")
    tickets: List[TaskTicket] = Field(default_factory=list)
    execution_order: List[List[str]] = Field(
        default_factory=list,
        description="Batches of ticket IDs that can be executed in parallel"
    )


class KanbanColumn(BaseModel):
    name: str = Field(...)
    ticket_ids: List[str] = Field(default_factory=list)


class KanbanState(BaseModel):
    """Active Kanban board state."""
    sprint_number: int = Field(default=1)
    columns: Dict[str, List[str]] = Field(
        default_factory=lambda: {
            "backlog": [],
            "in_progress": [],
            "in_review": [],
            "done": [],
            "blocked": []
        }
    )
    total_tickets: int = Field(default=0)
    completed_tickets: int = Field(default=0)
